### ISSUE TITLE
Unable to add subordinate's B-set

### ISSUE THREAD

**Issue by drosta99** [meinemitternacht/cdcmastery#17]
I can't see or view the request for my subordinate's request for added material. On his/her account, it explains that the process requires approval from the supervisor. I, as the supervisor, am unable to see or view this request. Am I doing it wrong?

**Comment by meinemitternacht** [comment]
Are you referring to the text on the https://cdcmastery.com/profile/afsc page? AFSC approval requires an Administrator or Training Manager, supervisors are only able to view their subordinate's test history.

I went ahead and approved access, but let me know if you need anything else!
