### ISSUE TITLE
Editing flashcards with line breaks adds more line breaks

### ISSUE THREAD

**Issue by parasprite** [meinemitternacht/cdcmastery#2]
For example. if you have the following flashcard:

    A line of text
    Another line of text

The edit page will show

    A line of text<br \>
    Another line of text

If you save that as-is, it will add a second line break (one for the newline character and one for the tag).

Ideally the <br \> shouldn't be shown to the user at all, but baring that at least something to prevent duplicate breaks would be nice. Otherwise you have to keep removing the <br \> tags in edit mode.

**Comment by meinemitternacht** [comment]
@parasprite thanks for identifying these issues.  I'm currently in the middle of a rewrite of the entire site, but I have no timeline on when that will be done.  As this is purely a side project, I can only devote time to it when I don't have other projects going on.  I'll give a milestone to all of these and hopefully they will all be resolved during the rewrite.

**Comment by meinemitternacht** [comment]
I have verified this is fixed in the new version of the site (yet to be released).  Even if you are not still utilizing the site, hopefully someone else will benefit from the changes.
