### ISSUE TITLE
WPNS (2w1) CDC Mastery

### ISSUE THREAD

**Issue by JKRidley** [meinemitternacht/cdcmastery#25]
Good evening, 

     I am aware that CDC Mastery will be disabled on December 31st. However, I would still like access to all of the questions and answers to continue my studies. The Study material I am asking for is as follows: 2w151, 2w151A EC07, 2w151b, 2w151B EC07, and 2w171. Is there a way someone from your team could send me a document with all of the questions and answers? This would be a tremendous help on my quest to learning all of the material. Thank you! 

V/R, 
Jaquavius K. Ridley

**Comment by meinemitternacht** [comment]
Please check back on the site to sign up again. The shutdown has been postponed.
