### ISSUE TITLE
(Request, minor, probably easy) Add autofocus attribute to cardFrontText (Add flash cards)

### ISSUE THREAD

**Issue by parasprite** [meinemitternacht/cdcmastery#6]
Reason: Improve workflow as you can just start typing. 

I know there's a rewrite coming eventually, but this would help speed up writing all these cards.

Thanks

**Comment by meinemitternacht** [comment]
I added this to the site a few minutes ago, let me know if you do not see the change.

**Comment by parasprite** [comment]
Works perfectly. Thanks again :)
